### ISSUE TITLE
Ingress parsing error when installing with helm

### ISSUE THREAD

**Issue by edalford11** [stakater/GitWebhookProxy#38]
Followed the directions exactly how it instructs on the readme. Only changed the host, upstreamURL and allowedPaths as instructed.

`Error: release gitwebhookproxy failed: Ingress in version "v1beta1" cannot be handled as a Ingress: v1beta1.Ingress.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|edirect":true,"kuber|..., bigger context ...|ons":{"ingress.kubernetes.io/force-ssl-redirect":true,"kubernetes.io/ingress.class":"ingress-externa|...`

**Comment by rasheedamir** [comment]
@hazim1093 can you plz take a look?

**Comment by kahootali** [comment]
@edalford11 can you please specify which version of k8s are you using?

**Comment by edalford11** [comment]
Woops forgot to list the versions sorry about that @kahootali 

Kubernetes: 1.10.5
Helm: 2.10.0

```yaml
kubernetes:
  host: https://kubernetes.default

gitWebhookProxy:
  namespace: kube-system
  labels:
    provider: stakater
    group: com.stakater.platform
    version: 0.2.42
  image:
    name: stakater/gitwebhookproxy
    tag: "0.2.42"
    pullPolicy: IfNotPresent
  config:
    provider: github
    upstreamURL: "http://my-url"
    allowedPaths: "/github-webhook/"
#    secret: "dummysecret"
#    ignoredUsers: "stakater-user"
  service: 
    forceSslRedirect: true
    ingressClass: ingress-external
    expose: true
    additionalIngressAnnotations: 
      - key: monitor.stakater.com/enabled
        value: true
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080
  ingress:
    annotations:
      - key: ingress.kubernetes.io/force-ssl-redirect
        value: "true"
      - key: kubernetes.io/ingress.class
        value: ingress-external
      - key: monitor.stakater.com/enabled
        value: "true"
    host: subdomain.domain.com
    serviceName: gitwebhookproxy
    servicePort: 80
```
